### Get events list
GET http://localhost:8000/api/events

### Get all events
GET http://localhost:8000/api/events/all

### Create event
POST http://localhost:8000/api/events
content-Type: application/json

{
  "name": "Test event 2",
  "location": "Tallinn",
  "date": "2022-02-25T16:10:03.376Z",
  "type": "concert"
}

### Get ticket
GET  http://localhost:8000/api/tickets/1

### Get tickets
GET  http://localhost:8000/api/tickets

### Create ticket
POST http://localhost:8000/api/tickets
content-Type: application/json

{
  "validationCode": 12345678,
  "event": 2
}


### Sell ticket
PATCH http://localhost:8000/api/tickets/3/sell
content-Type: application/json

{
  "sold": true
}

### Validate ticket
PATCH http://localhost:8000/api/tickets/validate
content-Type: application/json

{
  "validationCode": 12345678
}